### ISSUE TITLE
Coordinates only added from inventory file when "decimate" is checked.

### ISSUE THREAD

**Issue by aklesh** [paddy-seismic/retreat#5]
At line 100 in retreat/data/array_preproc.py, the "add coordinates" block is inappropriately tabbed under the "decimate" if-block, causing an error to be thrown if "decimate" is not selected. Fix is to move the coordinates block to the left 4 spaces.

**Comment by paddy-seismic** [comment]
Hi aklesh, many thanks for this. Got round to fixing this eventually..!
